### ISSUE TITLE
Как запустить модуль на DLE 15 ?

### ISSUE THREAD

**Issue by aazzz** [dle-modules/DLE-UniForm#107]
# Описание ошибки:
Fatal error: Uncaught Error: Class 'HTMLPurifier_Config' not found in /var/www/poker/data/www/pokerblog.ru/engine/classes/parse.class.php:61 Stack trace: #0 /var/www/poker/data/www/pokerblog.ru/engine/modules/uniform/uniform.php(96): ParseFilter->__construct() #1 /var/www/poker/data/www/pokerblog.ru/engine/ajax/uniform.php(99): include('/var/www/poker/...') #2 /var/www/poker/data/www/pokerblog.ru/engine/ajax/controller.php(196): include_once('/var/www/poker/...') #3 {main} thrown in /var/www/poker/data/www/pokerblog.ru/engine/classes/parse.class.php on line 61
При каких условиях воспроизводится ошибка: 
после клика на кнопку отправить
Страница, на которой наблюдается ошибка:
https://pokerblog.ru/about.html

**Comment by m3tam0rph** [comment]
в modules/uniform.php
перед 			
require_once (DLEPlugins::Check(ENGINE_DIR . '/classes/parse.class.php'));
вставить
include_once (DLEPlugins::Check(ENGINE_DIR . '/classes/htmlpurifier/HTMLPurifier.standalone.php'));

**Comment by aazzz** [comment]
Спасибо, заработал :)
